apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: production-gsheet-api
  namespace: argocd
  labels:
    type: app
spec:
  syncPolicy:
    automated:
      selfHeal: true
  project: myproject-production
  source:
    repoURL: git@github.com:melalj/gitops-sample.git
    targetRevision: HEAD
    path: charts/app/gsheet-api
    helm:
      releaseName: gsheet-api
      valueFiles:
      - values-production.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: production
