image:
  repository: tonoid/myproject-frontend
  tag: "staging-473ba07" # 2021-11-18T15:27:39Z https://circleci.com/gh/melalj/myproject-frontend/34

containerPort: 80

deployment:
  env:
    normal:
      PROJECT_ENV: "staging"

service:
  type: LoadBalancer
  name: "frontend-staging"