image:
  repository: tonoid/myproject-frontend
  tag: "production-473ba07" # 2021-11-18T15:26:50Z https://circleci.com/gh/melalj/myproject-frontend/33

containerPort: 80

replicaCount: 1

deployment:
  env:
    normal:
      PROJECT_ENV: "production"

service:
  type: LoadBalancer
  name: "frontend-production"