image:
  repository: tonoid/myproject-frontend
  tag: "production-6c61ad0" # 2021-11-17T22:07:31Z https://circleci.com/gh/melalj/myproject-frontend/18

containerPort: 80

replicaCount: 1

deployment:
  env:
    normal:
      PROJECT_ENV: "production"

service:
  type: LoadBalancer
  name: "frontend-production"