image:
  repository: tonoid/myproject-frontend
  tag: "production-2e4a94e" # 2021-11-18T10:46:52Z https://circleci.com/gh/melalj/myproject-frontend/20

containerPort: 80

replicaCount: 1

deployment:
  env:
    normal:
      PROJECT_ENV: "production"

service:
  type: LoadBalancer
  name: "frontend-production"