image:
  repository: env-test/myproject-frontend
  tag: "production-879ed13" # 2022-06-16T07:49:53Z https://circleci.com/gh/env-test/myproject-frontend/12

containerPort: 80

replicaCount: 1

deployment:
  env:
    normal:
      PROJECT_ENV: "production"

service:
  type: LoadBalancer
  name: "frontend-production"
