image:
  repository: tonoid/myproject-frontend
  tag: "production-49526e8" # 2022-06-16T06:50:22Z https://circleci.com/gh/env-test/myproject-frontend/8

containerPort: 80

replicaCount: 1

deployment:
  env:
    normal:
      PROJECT_ENV: "production"

service:
  type: LoadBalancer
  name: "frontend-production"