image:
  repository: tonoid/myproject-frontend
  tag: "staging-04a73e4" # 2021-11-17T16:43:16Z https://circleci.com/gh/melalj/myproject-frontend/12

containerPort: 80

deployment:
  env:
    normal:
      PROJECT_ENV: "staging"

service:
  type: LoadBalancer
  name: "frontend-staging"