image:
  repository: tonoid/myproject-frontend
  tag: "production-1e47491" # 2021-11-18T11:16:57Z https://circleci.com/gh/melalj/myproject-frontend/26

containerPort: 80

replicaCount: 1

deployment:
  env:
    normal:
      PROJECT_ENV: "production"

service:
  type: LoadBalancer
  name: "frontend-production"