image:
  repository: tonoid/myproject-frontend
  tag: "production-f3ef092" # 2021-11-18T11:32:49Z https://circleci.com/gh/melalj/myproject-frontend/29

containerPort: 80

replicaCount: 1

deployment:
  env:
    normal:
      PROJECT_ENV: "production"

service:
  type: LoadBalancer
  name: "frontend-production"