image:
  repository: tonoid/myproject-frontend
  tag: "staging-2e4a94e" # 2021-11-18T10:49:57Z https://circleci.com/gh/melalj/myproject-frontend/22

containerPort: 80

deployment:
  env:
    normal:
      PROJECT_ENV: "staging"

service:
  type: LoadBalancer
  name: "frontend-staging"