image:
  repository: tonoid/myproject-frontend
  tag: "production-a1268fb" # 2021-11-17T21:47:50Z https://circleci.com/gh/melalj/myproject-frontend/14

containerPort: 80

replicaCount: 1

deployment:
  env:
    normal:
      PROJECT_ENV: "production"

service:
  type: LoadBalancer
  name: "frontend-production"