image:
  repository: tonoid/myproject-frontend
  tag: "staging-f3ef092" # 2021-11-18T11:32:39Z https://circleci.com/gh/melalj/myproject-frontend/30

containerPort: 80

deployment:
  env:
    normal:
      PROJECT_ENV: "staging"

service:
  type: LoadBalancer
  name: "frontend-staging"