image:
  repository: env-test/myproject-frontend
  tag: "production-49526e8" # 2022-06-16T07:17:15Z https://circleci.com/gh/env-test/myproject-frontend/10

containerPort: 80

replicaCount: 1

deployment:
  env:
    normal:
      PROJECT_ENV: "production"

service:
  type: LoadBalancer
  name: "frontend-production"
