image:
  repository: tonoid/myproject-frontend
  tag: "staging-a1268fb" # 2021-11-17T21:49:54Z https://circleci.com/gh/melalj/myproject-frontend/16

containerPort: 80

deployment:
  env:
    normal:
      PROJECT_ENV: "staging"

service:
  type: LoadBalancer
  name: "frontend-staging"