image:
  repository: tonoid/myproject-frontend
  tag: "production-42aa186" # 2021-11-18T11:05:26Z https://circleci.com/gh/melalj/myproject-frontend/24

containerPort: 80

replicaCount: 1

deployment:
  env:
    normal:
      PROJECT_ENV: "production"

service:
  type: LoadBalancer
  name: "frontend-production"