image:
  repository: tonoid/myproject-frontend
  tag: "production-04a73e4" # 2021-11-17T16:35:18Z https://circleci.com/gh/melalj/myproject-frontend/10

containerPort: 80

replicaCount: 1

deployment:
  env:
    normal:
      PROJECT_ENV: "production"

service:
  type: LoadBalancer
  name: "frontend-production"