image:
  repository: tonoid/myproject-frontend
  tag: "staging-79a8cd0" # 2022-06-16T07:52:16Z https://circleci.com/gh/env-test/myproject-frontend/14

containerPort: 80

deployment:
  env:
    normal:
      PROJECT_ENV: "staging"

service:
  type: LoadBalancer
  name: "frontend-staging"