apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: myproject-production
  namespace: argocd
spec:
  description: myproject production
  sourceRepos:
  - '*'
  destinations:
  - namespace: '*'
    server: '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'