apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: myproject-staging
  namespace: argocd
spec:
  description: myproject staging
  sourceRepos:
  - '*'
  destinations:
  - namespace: '*'
    server: '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'