apiVersion: v1
kind: Secret
metadata:
  name: app
  namespace: production # edit this for staging
type: Opaque
data:
  MY_SECRET_VAR: "Ym9uam91ciBtYWRhbWU=" # base64 encoded
  GOOGLE_CREDENTIALS: "****" # base64 encoded
