image:
  repository: tonoid/myproject-api
  tag: "staging-d9302eb" # 2021-11-17T17:07:13Z https://circleci.com/gh/melalj/myproject-api/15

containerPort: 80

deployment:
  env:
    normal:
      PROJECT_ENV: "production"
      MY_VARIABLE: "1"